### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by milotype** [FineFindus/eyedropper#103]
**Describe the bug**
1. In the section [Translation](https://github.com/FineFindus/eyedropper#translation) in the [README.md](https://github.com/FineFindus/eyedropper/blob/master/README.md) file on the project page at Github you state that one could use [Weblate](https://hosted.weblate.org/projects/eyedropper/eyedropper/) for translations. Unfortunately, the project is currently locked and translators can only suggest translations.

2. I've looked through other langages and found out that they don't have the same number of translatable strings as defined in the current **Eyedropper.pot** file. 
For my Croatian translation I've used the current .pot file on your GitHub project page with the following information in the header: `POT-Creation-Date: 2023-11-14 19:29+0000\n`. The file has **146** translatable strings.

Some suggestions which might help improve the two above issues (btw. I'm not a programmer):
- Update all existing .po files on GitHub with the current .pot file so they all have the same number of translatable strings. (Take a look at my section "SOULTION" below.)
- Upload all those changed files to your project page at Weblate. (IMO, chances are way better that your project gets translated into even more languages at Weblate then through GitHub.)
- Unlock the project on Weblate in order to enable translating.

**SOLUTION**:
If you want, I could:
a) update the .po files for currently existing languages with the current .pot file and **keep** all unused/old/orphaned strings (de, es, eu, fr, it, nl, ru). _IMO useless because those strings are obsolete and keep the files larger then necessary._
b) update the .po files for currently existing languages with the current .pot file and **remove** all unused/old/orphaned strings (de, es, eu, fr, it, nl, ru). _IMO better, because deleting those strings keep the files smaller._

If you agree with one of the above solution, I could send a new Pull Request with changes for the .po files.
Let me know if you would like me to help you out with one of the above mentioned solutions.

Just some observations and ideas, even though the project is in a trial period.
I hope they are helpfull :-)

Cheers,
Milo

**Comment by FineFindus** [comment]
Thanks for the feedback.
I'm aware that Weblate is currently unavailable. This is due to the fact that the project is still in the trial period, and I get regular emails about the imminent deletion of the project, so it didn't seem worth fixing yet.

As you may have noticed, the template file `Eyedropper.pot` is generated by the CI every time a string is changed in the application, so it is usually up-to-date. Individual languages having a different amount is either because the new strings have been added since, or the translation hasn't been updated in a while (usually happens before a new release).
The old strings are generated by the various tools used by the translator when those strings are removed. File size is not really an issue, the files are not overly long and are compiled for the application, stripping out unnecessary information, so I don't think it's necessary to remove old strings. But if you want to, feel free to do so.

Closing this, if you have further questions or disagree, feel free to reopen it.
