### ISSUE TITLE
"Failed to pick a color"

### ISSUE THREAD

**Issue by CSpencerND** [FineFindus/eyedropper#16]
When clicking on the eyedropper or pressing ctrl + p:
"Failed to pick a color" appears at the bottom of the window.

In the terminal:
ERROR eyedropper::window > Portal request didn't succeed: Other

This happens with flatpak and if built with gnome builder.

Only happens on window managers. Works fine on gnome.

- Fedora 36
- DWM, Hyprland

**Comment by FineFindus** [comment]
I guess that it is related to the usage of a window manager, since it works fine on Gnome

**Comment by CSpencerND** [comment]
> Did you test it on the same system with Gnome/the wms?
Yes.

**Comment by FineFindus** [comment]
Ok, I've looked into this (using DWM), it seems like this is an issue with the [portals API](https://github.com/flatpak/xdg-desktop-portal#using-portals). This is also an issue with similar color pickers, such as [gcolor3](https://gitlab.gnome.org/World/gcolor3).

As a workaround, I would recommend using another color picker (for example [hyprpicker](https://github.com/hyprwm/hyprpicker)) and just editing the hex format of the color.

**Comment by FineFindus** [comment]
So, I did a bit more research and came to the conclusion, that an unimplemented portal API should not be tracked here. I think the appropriate place for this issue would be more in the direction of [the portal GitHub page](https://github.com/emersion/xdg-desktop-portal-wlr).

Also, it seems like the latest commit implemented the needed screenshot portal, but they did have a new release since, so a new issue might not be necessary.

I'm closing this for now, if the picker still not works with the screenshot portal, or you disagree with my decision, feel free to reopen this issue.
