### ISSUE TITLE
Don't launch with an arbitrary `#2E3440` color, always show the current color in the sidebar to the right when there's more than two colors, and let me delete colors

### ISSUE THREAD

**Issue by nekohayo** [FineFindus/eyedropper#25]
I'm running the flatpak version from Flathub, on Fedora.
By default, the app launches like this, with color `#2E3440`:

![Screenshot from 2022-10-21 21-08-13](https://user-images.githubusercontent.com/479401/197309739-5b1fb120-4b78-4a0f-803b-09b7dce6ff4f.png)

This is a problem when I want to sample colors that actually are close to this, such as `#002E41`. I then basically can't tell stuff apart from your default color, and I can't clear/remove the default color. Additionally, when you click a color on the right it "swaps places" with the color details on the left, which then goes into the right, and it means the colors keep shifting around all the time, so if you have a couple of similar-looking colors it's absolutely impossible to keep track of because the list keeps being reordered.

Please have the app start with a blank slate with just a "Pick a color" button, then don't swap things around when I click them in the sidebar (they should rather act like tabs, functionally speaking) and if I made a mistake and picked the wrong color, let me right-click and delete it (or have a delete button in the color's details).

**Comment by FineFindus** [comment]
I think it is a reasonable request to have no default color / a different one, I just did not want to have the default white or black color.

The reason the color keeps 'swapping' places, is that, when you select a color from the history, it gets removed from the history and is shown with details instead, while the currently picked color gets added to the history. If you had multiple colors in the history, the effect would be more clearly visible.

I'm not sure how to deal with deleting the history (although a clear button will likely be included in the next release), since right click functions [are discouraged by the Gnome HIG](https://developer.gnome.org/hig/patterns/controls/buttons.html). I will have to think about that.

**Comment by FineFindus** [comment]
A clear action, to clear the whole history, has been added in the latest commit a3e949c62094a3882da991d2a26da9f60f324a44.
