### ISSUE TITLE
Differentiate entry from output

### ISSUE THREAD

**Issue by sophie-h** [FineFindus/eyedropper#44]
I find it very unsatisfactory that one line is an entry but the others are not. It feels so bad when clicking on them xD

@bertob you maybe have an idea for a tiny tiny bit of differentiation between the two types of rows?

**Comment by FineFindus** [comment]
I see the issues, I guess it never occurred to me, as I always knew which entry was clickable and which was not. While differentiating them is probably a good idea in the short term, I think a better long term solution would allow the user to click and enter data in all of them.
This was already on my to-do list for the long term (maybe never) plan, I will try to investigate this after this version is released.

**Comment by bertob** [comment]
> a better long term solution would allow the user to click and enter data in all of them.

Agreed, I was also wondering about that. I think it'd be a very useful and natural extension of the current feature set and fix the issue more elegantly than changing the styling on the non-editable ones.

**Comment by FineFindus** [comment]
As a quick update, it turns out that this is a bit more difficult than expected, as each color has to be parsed and converted to RGB, which is used under the hood. It's quite possible that I'll also rewrite the colour system, as it's becoming quite a mess with all the different formats.

I've opened a pull request with all the formats I've completed so far, and will keep track of its progress.
