### ISSUE TITLE
Colors very similar to window background blend in too much

### ISSUE THREAD

**Issue by bertini97** [FineFindus/eyedropper#58]
Picking up colors too similar to the window background makes them difficult to know they're been saved in the palette at all. See screenshot for an extreme case: there are two saved colors there.
![Schermata del 2023-03-22 08-48-07](https://user-images.githubusercontent.com/106469113/226835081-3c672f0e-fda8-4696-ad0b-e776ceef0374.png)
I suggest having a light `2px` border around them to make them stand out.

**Comment by FineFindus** [comment]
Thanks for the report, it's fixed in 74e2bc0237643b05244967b73b53e22ad4484b74. While the idea of a border is good, I solved it by adding a shadow to the color item, which is less intrusive.

| Light                                                                                                                                           	| Dark                                                                                                                                          	|
|-------------------------------------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------------------------------	|
| ![Light on light background with shadow](https://user-images.githubusercontent.com/63370021/229303240-137ceb65-74bf-4fe0-bb12-8c039f4c0523.png) 	| ![dark on dark background with shadow](https://user-images.githubusercontent.com/63370021/229303242-f6f531fd-b667-4517-983b-425cfee032b9.png) 	|
