### ISSUE TITLE
Portuguese translation not working on Ubuntu 23.04

### ISSUE THREAD

**Issue by narniano** [FineFindus/eyedropper#75]
Although there's a Portuguese translation on the LINGUAS file and my system is in Brazilian Portuguese. The app itself is in English, and Gnome Software says there isn't a translation for my language. 

I was available to translate the app for my language, but then I saw there's already one. Maybe the issue is happening because the LINGUAS file has a translation to Portuguese, not to Brazilian Portuguese. Or maybe there's a problem in the Flatpak integration with Ubuntu 23.04. I really don't know. 

**Screenshots**
![image](https://github.com/FineFindus/eyedropper/assets/107469259/032d31dd-ad83-4bd0-89f6-970dc9528edc)
![image](https://github.com/FineFindus/eyedropper/assets/107469259/0094de07-2e1d-4195-a6e6-b55e76e1965e)

**Information**

- OS: Ubuntu 23.04
- Desktop Environment: Gnome 44.2
- Version: 0.6.0

**Comment by FineFindus** [comment]
The Portuguese translation was added in https://github.com/FineFindus/eyedropper/pull/66, there hasn't been a stable release since then, so it's not available.
If you can't wait for the next stable release, you can use the [0.7.0-beta](https://github.com/FineFindus/eyedropper/releases/tag/v0.7.0-beta) which contains it.
